### ISSUE TITLE
Install instruction incorrect and Bower issues

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [MrBoolean/angular-confirm#2]
Example: <code><script src="path/to/angular-confirm/dist/angular-confirm.min.js"></script></code>
Actual: <code><script src="path/to/angular-confirm-button/dist/angular-confirm.min.js"></script></code>
Notice the: -button

Bower: Unable to find a suitable version for angular, please choose one:

That aside, great project, love it!

**Comment by m19c** [comment]
Hmmm... It seems that the rename of this project doesn't work correctly. 
I will investigate time in the next week to release a new major version with several tweaks e.g. amd, umd, system and jsx exports as well as a new release process. 
Thanks for your contribution ;-)

**Comment by m19c** [comment]
Sooo... 1.1.0 released. The project name has changed to "ng-confirm". It also comes with a bunch of exports (amd, amd-strict, ignore, strict, system, umd - minified and unminified). Pick your preferred export out of the dist/ folder.

Have fun!
